### ISSUE TITLE
Get from SLA Manager the NS flavour corresponding to a given SLA

### ISSUE THREAD

**Issue by carlos-f-parada** [sonata-nfv/tng-gtk-sp#260]
The purpose is to add the flavour as a parameter towards the MANO Framework on NS instantiation.
@ekapassa, please drop here the API details on the SLA Manager to be used by the GTK (@jbonnet) to invoke this mapping.

**Comment by ekapassa** [comment]
@carlos-f-parada  Here is the API information in order to receive the desired flavour, based on a selected NSD and the corresponding SLA:    

**API Endpoint:**     
`curl -v -H "Content-type:application/json" http://int-sp-ath.5gtango.eu:32002/api/v3/slas/configurations/<nsd_uuid>/<sla_uuid>`    

**API Response**    
`{"d_flavour_name":"Gold flavour",
"sla_uuid":"82f5c335-5925-41c7-a412-cdd7231b0c04",
"nsd_uuid":"f64b4aaa-4292-4e3b-a00e-df8446db22b8"}`

**Comment by carlos-f-parada** [comment]
@tsoenen, we need to define (if not yet) an additional NS deployment parameter for the flavour. Can you propose it and drop the datails here? (BTW, we have 2 other in the queue for NS instantiation optional parameters, list of VIMs and VL_names for Slicing purposes)

**Comment by tsoenen** [comment]
```
---
NSD: <...>
VNFD0: <...>
VNFD1: <...>
egresses: []
ingresses: []
blacklist: []
user_data: <...>
flavor: <string>
mapping:
  network_functions:
    - {'vnf_id': <string>, 'vim_id': <string>}
  virtual_links:
    - {'vl_id': <string>, 'external_net': <string>, 'vim_id': <string>}
```
@carlos-f-parada @jbonnet : What do you think of this as possible extension for the payload when the GK requests the MANO to instantiate a service? 

* I added a flavor key, so the flavor can be indicated as a string. If there is no flavor, the content should be nill
 * I also added the mapping object, which has two keys: `network_functions` and `virtual_links`. Both keys have a list as value. The list can be empty. Elements in the list are again an object. Objects in the `network_function` list have two keys: `vnf_id` (which is the vnf_id coming from the `network_function` list in the NSD) and `vim_id`, a uuid that indicates the VIM that the vnf should be deployed on. Objects in the `virtual_links` list have three keys: `vl_id` to indicate which vl it is (should map with NSD), `external_net` is the id of the external network that should be used for this vl and `vim_id` to indicate on which VIM the external net can be found.
